/**
 * The corpus: the decks the oracle is asked about.
 *
 * Every deck here is **generated by `@shbernal/ts-pptx` itself**, and that is not
 * a convenience — it is the v1 input domain. The guarantee is scoped to decks
 * this pipeline can write, so generating the corpus from the writer makes the
 * corpus and the guarantee's scope the same set. Decks authored in PowerPoint
 * are a second tier, deferred.
 *
 * They are built by code rather than committed as `.pptx` binaries so the corpus
 * is reviewable in a diff and reproducible from source. Nothing here may depend
 * on the clock, the filesystem or randomness: a corpus that differs between runs
 * makes every downstream comparison unfalsifiable.
 *
 * Two tiers:
 *
 * - `primitive` — one deck per emit primitive. These are the constructs the IR
 *   is expected to model, so a difference is a defect.
 * - `hard` — one deck per known-hard feature. These are expected to take the
 *   carried lane or to arrive with fidelity notes at first; they are here so the
 *   coverage report can watch them move, not because they must pass today.
 */

import { ShapeType, TsPptx } from '@shbernal/ts-pptx'

/** A 1×1 PNG. Content is irrelevant; being real, small and constant is not. */
const PIXEL_PNG =
	'image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='

export type CorpusTier = 'primitive' | 'hard'

export interface CorpusDeck {
	/** Stable id — used as a snapshot key, so renaming one rewrites history. */
	name: string
	tier: CorpusTier
	/** What this deck is here to hold the pipeline to. */
	why: string
	build: () => Promise<Uint8Array>
}

/** A writer with deterministic deck properties: no clock, no host, no defaults that drift. */
function newDeck(): TsPptx {
	const pptx = new TsPptx()
	pptx.layout = 'LAYOUT_16x9'
	pptx.author = 'pptx-html corpus'
	pptx.company = 'pptx-html'
	pptx.subject = 'round-trip corpus'
	pptx.title = 'round-trip corpus'
	return pptx
}

async function bytesOf(pptx: TsPptx): Promise<Uint8Array> {
	return (await pptx.write({ outputType: 'uint8array' })) as Uint8Array
}

function deck(name: string, tier: CorpusTier, why: string, author: (pptx: TsPptx) => void | Promise<void>): CorpusDeck {
	return {
		name,
		tier,
		why,
		build: async () => {
			const pptx = newDeck()
			await author(pptx)
			return bytesOf(pptx)
		},
	}
}

export const CORPUS: CorpusDeck[] = [
	deck('text-box', 'primitive', 'runs, paragraph breaks and per-run character formatting', (pptx) => {
		pptx.addSlide().addText(
			[
				{ text: 'Round', options: { bold: true, color: '250F6B' } },
				{ text: '-trip', options: { italic: true, color: '9B1B30' } },
				{ text: '\nsecond paragraph', options: { breakLine: true, fontSize: 14 } },
			],
			{ x: 0.5, y: 0.5, w: 6, h: 2, fontSize: 24, align: 'left', objectName: 'copy' }
		)
	}),

	deck('autoshape', 'primitive', 'a preset geometry with an explicit fill and outline', (pptx) => {
		pptx.addSlide().addShape('roundRect', {
			x: 1,
			y: 1,
			w: 3,
			h: 1.5,
			fill: { color: 'DDE3F0' },
			line: { color: '250F6B', width: 2 },
			rectRadius: 0.2,
			objectName: 'card',
		})
	}),

	deck('preset-geometry', 'primitive', 'the three presets beyond the rectangle family, one of them curved', (pptx) => {
		// `render.test.ts` asserts the corpus draws every geometry it uses with no box
		// standing in. That claim is only as wide as the corpus, and until this deck
		// existed it reached `rect`, `roundRect`, `triangle`, `line` and a freeform —
		// so the presets whose formulas are the easiest to get subtly wrong were the
		// ones nothing exercised end to end. Their paths are pinned exactly in
		// `test/unit/render-geometry.test.ts`; this is the half that runs them through
		// a real deck, where an adjust value has to survive the loop to reach them.
		// Every one states an adjust rather than taking the preset's default, so the
		// deck pins that `a:avLst` survives the loop and reaches the formula. A deck
		// of defaults would draw the same picture whether the adjust were read or
		// dropped, which is the assertion quietly worth nothing.
		const slide = pptx.addSlide()
		slide.addShape('chevron', {
			x: 0.5,
			y: 0.5,
			w: 3,
			h: 1.2,
			fill: { color: 'DDE3F0' },
			shapeAdjust: { name: 'adj', value: 0.3 },
			objectName: 'step',
		})
		slide.addShape('star5', {
			x: 4,
			y: 0.5,
			w: 1.5,
			h: 1.5,
			fill: { color: 'F0C808' },
			shapeAdjust: { name: 'adj', value: 0.3 },
			objectName: 'rating',
		})
		// 180° → 90° is a three-quarter sweep, which crosses the large-arc threshold
		// the other two shapes never reach.
		slide.addShape('blockArc', {
			x: 0.5,
			y: 2.5,
			w: 2.5,
			h: 2.5,
			fill: { color: '250F6B' },
			angleRange: [180, 90],
			arcThicknessRatio: 0.2,
			objectName: 'gauge',
		})
	}),

	deck('custgeom', 'primitive', 'freeform path geometry — the case the SVG vectorizer produces', (pptx) => {
		pptx.addSlide().addShape(ShapeType.custGeom, {
			x: 1,
			y: 1,
			w: 3,
			h: 3,
			fill: { color: '9B1B30' },
			points: [
				{ x: 0, y: 0, moveTo: true },
				{ x: 3, y: 0 },
				{ x: 3, y: 3, curve: { type: 'cubic', x1: 2.5, y1: 1, x2: 2, y2: 2 } },
				{ close: true },
			],
			objectName: 'freeform',
		})
	}),

	deck('table', 'primitive', 'a grid with per-cell formatting and explicit column widths', (pptx) => {
		pptx.addSlide().addTable(
			[
				[
					{ text: 'Region', options: { bold: true, fill: { color: '250F6B' }, color: 'FFFFFF' } },
					{ text: 'Share', options: { bold: true, fill: { color: '250F6B' }, color: 'FFFFFF' } },
				],
				[{ text: 'EMEA' }, { text: '48%' }],
				[{ text: 'AMER' }, { text: '31%' }],
			],
			{ x: 0.5, y: 0.5, w: 6, colW: [3, 3], border: { type: 'solid', color: 'CCCCCC', width: 1 }, objectName: 'grid' }
		)
	}),

	deck('cell-fill', 'primitive', 'a table cell that suppresses its fill next to one that states none', (pptx) => {
		// The two cells in the second row differ only in their `a:tcPr`: `clear` states
		// `a:noFill`, `plain` states nothing. They paint differently — one lets the
		// slide through, the other takes the table style's shading — so a lane that
		// reports the same fill for both has flattened a real difference.
		//
		// Reachable only since ts-pptx 3.1.0, and by two fixes at once:
		// `fill: { type: 'none' }` authors the `a:noFill`
		// (https://github.com/shbernal/ts-pptx/issues/9) and `TableCell.fillNoFill`
		// reads it back (https://github.com/shbernal/ts-pptx/issues/7). Before that
		// the deck could not be written and its distinction could not be read.
		pptx.addSlide().addTable(
			[
				[{ text: 'Stated', options: { fill: { color: '250F6B' }, color: 'FFFFFF' } }, { text: 'Suppressed' }],
				[{ text: 'plain' }, { text: 'clear', options: { fill: { type: 'none' } } }],
			],
			{ x: 0.5, y: 0.5, w: 6, colW: [3, 3], objectName: 'cells' }
		)
	}),

	deck('picture', 'primitive', 'embedded media — the case hash-addressed assets must survive', (pptx) => {
		pptx.addSlide().addImage({ data: PIXEL_PNG, x: 1, y: 1, w: 2, h: 2, objectName: 'photo' })
	}),

	deck('connector', 'primitive', 'a line with routing and an arrowhead, not a shape', (pptx) => {
		pptx.addSlide().addConnector({
			type: 'elbow',
			x1: 1,
			y1: 1,
			x2: 5,
			y2: 3,
			color: '250F6B',
			width: 2,
			endArrowType: 'triangle',
			objectName: 'link',
		})
	}),

	deck('gradient', 'primitive', 'a multi-stop gradient fill — no single colour to fall back on', (pptx) => {
		pptx.addSlide().addShape('rect', {
			x: 0.5,
			y: 0.5,
			w: 8,
			h: 2,
			fill: {
				type: 'gradient',
				gradient: {
					kind: 'linear',
					angle: 45,
					stops: [
						{ position: 0, color: '250F6B' },
						{ position: 50, color: '4A3F9B' },
						{ position: 100, color: '9B1B30' },
					],
				},
			},
			objectName: 'banner',
		})
	}),

	deck('group', 'primitive', 'nested shape identity — a note about a child must still match', (pptx) => {
		pptx
			.addSlide()
			.addGroup(
				[
					{ rect: { x: 1, y: 1, w: 2, h: 1, fill: { color: 'DDE3F0' }, objectName: 'group-plate' } },
					{ text: { text: 'Grouped', options: { x: 1.1, y: 1.1, w: 1.8, h: 0.8, objectName: 'group-label' } } },
				],
				{ objectName: 'cluster' }
			)
	}),

	deck(
		'nested-group',
		'primitive',
		'a group inside a group — the depth where child coordinate space goes wrong',
		(pptx) => {
			pptx.addSlide().addGroup(
				[
					{ rect: { x: 0.5, y: 0.5, w: 1, h: 1, fill: { color: 'DDE3F0' }, objectName: 'outer-plate' } },
					{
						group: {
							children: [
								{ rect: { x: 2, y: 0.8, w: 1, h: 0.6, fill: { color: '250F6B' }, objectName: 'inner-plate' } },
								{ text: { text: 'Deep', options: { x: 2.1, y: 0.85, w: 0.8, h: 0.5, objectName: 'inner-label' } } },
							],
							options: { objectName: 'inner' },
						},
					},
				],
				{ objectName: 'outer' }
			)
		}
	),

	deck(
		'hyperlink',
		'primitive',
		'a run whose link points at another slide — an identity the IR must resolve',
		(pptx) => {
			pptx
				.addSlide()
				.addText([{ text: 'Jump to the appendix', options: { hyperlink: { slide: 2, tooltip: 'Appendix' } } }], {
					x: 1,
					y: 1,
					w: 6,
					h: 1,
					objectName: 'link-source',
				})
			pptx.addSlide().addText([{ text: 'External', options: { hyperlink: { url: 'https://example.invalid/spec' } } }], {
				x: 1,
				y: 1,
				w: 6,
				h: 1,
				objectName: 'link-target',
			})
		}
	),

	deck(
		'line-cap',
		'primitive',
		'a:ln/@cap — geometry on a thick dashed rule, and a write/read pair the script tier drops',
		(pptx) => {
			// The cap is the point, so the rule is thick and dashed: at 6pt a round cap
			// extends every dash by the stroke width and turns each one from a rectangle
			// into a lozenge. On a hairline the difference would be unobservable and the
			// deck would pass whether or not the attribute survived.
			//
			// As of ts-pptx 3.1.0 this gates the script tier for real: `readModelToIr`
			// consumes `Shape.lineCap` (https://github.com/shbernal/ts-pptx/issues/8),
			// so a dropped `@cap` now shows up as a difference instead of cancelling on
			// both sides of `diffDeckIr`. Before that the deck passed *while losing the
			// cap*, and earned its place on the import side alone, where `import.test.ts`
			// pins the cap the paint model carries.
			pptx.addSlide().addShape('line', {
				x: 1,
				y: 1,
				w: 6,
				h: 0,
				line: { color: '250F6B', width: 6, dashType: 'dash', cap: 'round' },
				objectName: 'rule',
			})
		}
	),

	deck('bullet', 'primitive', 'a numbered list’s startAt and the bullet’s own font, size and colour', (pptx) => {
		// `numberStartAt` is content, not styling: a list continuing "5. Deploy" that
		// comes back as "1. Deploy" is a different slide. The glyph's own font/size/
		// colour are here because they style the *bullet* rather than the run, so no
		// run property carries them and only `bulletDetail` reaches them at all.
		const slide = pptx.addSlide()
		slide.addText([{ text: 'Deploy' }], {
			x: 1,
			y: 1,
			w: 6,
			h: 1,
			bullet: {
				type: 'number',
				numberType: 'arabicPeriod',
				numberStartAt: 5,
				fontFace: 'Wingdings',
				size: 80,
				color: 'C00000',
			},
			objectName: 'steps',
		})
		// A picture bullet (`a:buBlip`) — the fourth kind, which the tagged-string
		// accessor dropped to `null` entirely. It is here as a *declared* loss: the
		// paint model resolves the image and can draw it, and upstream's text mapper
		// has no asset resolver, so the script tier notes `text.bullet.picture` and
		// falls back to a character. Watching that note stay declared is the point.
		slide.addText([{ text: 'Starred' }], {
			x: 1,
			y: 2.5,
			w: 6,
			h: 1,
			bullet: { image: { data: PIXEL_PNG } },
			objectName: 'starred',
		})
	}),

	deck(
		'autofit-shrink',
		'primitive',
		'a frame that bakes the scale PowerPoint shrank it by, beside one that does not',
		(pptx) => {
			const slide = pptx.addSlide()
			// The object form of `fit` bakes both attributes; the bare string writes
			// `<a:normAutofit/>` and no numbers. Both are `autofit: 'shrink'` in the
			// model and they have to paint differently — the first at 70% of 28pt, the
			// second at 28pt, which is also what PowerPoint shows until the frame is
			// edited.
			slide.addText(
				[{ text: 'Baked to seventy percent' }, { text: '\nand a second line', options: { breakLine: true } }],
				{
					x: 0.5,
					y: 0.5,
					w: 4,
					h: 1.2,
					fontSize: 28,
					fit: { type: 'shrink', fontScale: 70, lnSpcReduction: 20 },
					objectName: 'baked',
				}
			)
			// The reduction has a stated percentage to subtract from here, and none in
			// the frame above. Those are the two arms, and only the second is a guess.
			slide.addText([{ text: 'Spaced, then reduced' }], {
				x: 0.5,
				y: 2,
				w: 4,
				h: 1.2,
				fontSize: 28,
				lineSpacingMultiple: 1.5,
				fit: { type: 'shrink', fontScale: 62.5, lnSpcReduction: 10 },
				objectName: 'spaced',
			})
			slide.addText([{ text: 'Shrink, unmeasured' }], {
				x: 5,
				y: 0.5,
				w: 4,
				h: 1.2,
				fontSize: 28,
				fit: 'shrink',
				objectName: 'unbaked',
			})
		}
	),

	deck(
		'text-decoration',
		'primitive',
		'underline and strike in all six states, including the explicit “off” that means something',
		(pptx) => {
			// The two properties the editable surface exposes beside `bold` and `italic`.
			// Each models three values, and the third — `none` / `noStrike` — is the one
			// worth authoring: it is invisible on this slide and not the same fact as
			// stating nothing, because a run that inherits an underline from its
			// placeholder and states `u="none"` is not underlined.
			//
			// `strike: 'noStrike'` was a cast until ts-pptx 3.1.0+b16fb74b: the option
			// was typed `boolean | 'sngStrike' | 'dblStrike'`, so the explicit off had
			// no declared spelling even though the serializer wrote it correctly. The
			// union carries it now, so the literal below is the plain one.
			pptx.addSlide().addText(
				[
					{ text: 'single underline', options: { underline: { style: 'sng' }, breakLine: true } },
					{ text: 'double underline', options: { underline: { style: 'dbl' }, breakLine: true } },
					{ text: 'explicitly not underlined', options: { underline: { style: 'none' }, breakLine: true } },
					{ text: 'single strike', options: { strike: 'sngStrike', breakLine: true } },
					{ text: 'double strike', options: { strike: 'dblStrike', breakLine: true } },
					{ text: 'explicitly not struck', options: { strike: 'noStrike' } },
				],
				{ x: 0.5, y: 0.5, w: 6, h: 3, fontSize: 18, objectName: 'decorated' }
			)
		}
	),

	deck(
		'paragraph-align',
		'primitive',
		'the four alignments a paragraph can state, one paragraph that states none, and a two-run paragraph',
		(pptx) => {
			// `align` is one half of the paragraph tier of the editable surface;
			// `paragraph-bullet` below is the other.
			//
			// The last paragraph is the one worth having. `groupRunsIntoLines` starts a
			// new paragraph wherever two adjacent runs disagree about their alignment,
			// so a paragraph whose runs all agree is what proves the edit path writes
			// the value onto every run of a paragraph rather than onto the first — get
			// that wrong and this frame comes back with five paragraphs, not four.
			pptx.addSlide().addText(
				[
					{ text: 'left', options: { align: 'left', breakLine: true } },
					{ text: 'centre', options: { align: 'center', breakLine: true } },
					{ text: 'right', options: { align: 'right', breakLine: true } },
					{ text: 'justified across the width of the frame', options: { align: 'justify', breakLine: true } },
					{ text: 'two runs, ', options: { align: 'center' } },
					{ text: 'one paragraph', options: { align: 'center', bold: true } },
				],
				{ x: 0.5, y: 0.5, w: 6, h: 3, fontSize: 16, objectName: 'aligned' }
			)
		}
	),

	deck(
		'paragraph-bullet',
		'primitive',
		'the three things a paragraph can say about its bullet, including saying nothing',
		(pptx) => {
			// The other half of the paragraph tier, and the deck that needs a master to
			// mean anything: *inherited* and *explicitly none* differ only in whether
			// the list style still reaches the paragraph, so a frame with nothing above
			// it to inherit from would paint all three of these the same and pass while
			// losing the distinction entirely.
			//
			// `bullet: 'inherit'` writes no `a:pPr` at all. It is what ts-pptx#15 added:
			// before it, both the first and second paragraphs here emitted
			// `<a:pPr indent="0" marL="0"><a:buNone/></a:pPr>` and this deck could not
			// have been authored.
			pptx.defineSlideMaster({
				title: 'CORPUS_BULLETED_MASTER',
				objects: [
					{ placeholder: { options: { name: 'body', type: 'body', x: 0.5, y: 0.8, w: 9, h: 3 }, text: 'Body' } },
				],
			})
			pptx.addSlide({ masterTitle: 'CORPUS_BULLETED_MASTER' }).addText(
				[
					{ text: 'inherits the master’s bullet', options: { bullet: 'inherit', breakLine: true } },
					{ text: 'explicitly has none', options: { bullet: false, breakLine: true } },
					{ text: 'states its own glyph', options: { bullet: { characterCode: '25BA' }, breakLine: true } },
					// Two runs sharing one paragraph, for the same reason `paragraph-align`
					// has a pair: a paragraph property written to one run of a paragraph
					// splits it, and the run count does not move when it does.
					{ text: 'two runs, ', options: { bullet: 'inherit' } },
					{ text: 'one bullet', options: { bullet: 'inherit', bold: true } },
				],
				{ placeholder: 'body', objectName: 'bulleted' }
			)
		}
	),

	deck(
		'master-background',
		'primitive',
		'a slide whose whole chain states no background — the surface has to be white',
		(pptx) => {
			// The writer's built-in master authors a background, so reaching the unstated
			// case takes a `defineSlideMaster` that omits one. That is not an exotic deck:
			// it is what every custom master without an explicit `background` produces, and
			// the renderer painted all of them a flat grey until this deck existed.
			pptx.defineSlideMaster({
				title: 'CORPUS_BARE_MASTER',
				objects: [
					{ placeholder: { options: { name: 'title', type: 'title', x: 0.5, y: 0.4, w: 9, h: 1 }, text: 'Title' } },
				],
			})
			pptx.addSlide({ masterTitle: 'CORPUS_BARE_MASTER' }).addText('On an unstated surface', { placeholder: 'title' })
		}
	),

	deck(
		'layout-chrome',
		'primitive',
		'a layout’s non-placeholder furniture — drawn beneath the slide, editable nowhere',
		(pptx) => {
			// `defineSlideMaster({ objects })` writes every non-`placeholder` member into
			// the *layout* part (its own doc comment says so), so this is the one shape a
			// generated corpus can put outside a slide's own tree at all. Three of them,
			// each answering a different question:
			//
			//   band     a filled rect — does inherited furniture reach the picture
			//   wordmark text on a template tier — is it drawn but not typeable
			//   title    a placeholder — is it *excluded*, since the slide's own title
			//            already carries the geometry it inherited from this one
			//
			// The band is at the top edge and the wordmark inside it, both clear of the
			// slide's own shape, so a preview that drops the chrome differs visibly
			// rather than by a few pixels of overlap.
			pptx.defineSlideMaster({
				title: 'CORPUS_CHROME',
				background: { color: 'FFFFFF' },
				objects: [
					{ rect: { x: 0, y: 0, w: 10, h: 0.45, fill: { color: '250F6B' } } },
					{ text: { text: 'ACME', options: { x: 8.2, y: 0.05, w: 1.6, h: 0.35, color: 'FFFFFF', fontSize: 12 } } },
					{ placeholder: { options: { name: 'title', type: 'title', x: 0.5, y: 1, w: 9, h: 1 }, text: 'Title' } },
				],
			})
			pptx.addSlide({ masterTitle: 'CORPUS_CHROME' }).addText('Over the band', { placeholder: 'title' })
		}
	),

	deck('chart', 'hard', 'a full reader with no writer for every form — expected to be carried', (pptx) => {
		pptx.addSlide().addChart([{ name: 'Share', labels: ['EMEA', 'AMER', 'APAC'], values: [48, 31, 21] }], {
			type: 'bar',
			x: 1,
			y: 1,
			w: 6,
			h: 3.5,
			objectName: 'chart',
		})
	}),

	deck('layout-placeholder', 'hard', 'placeholder inheritance from a layout — no CSS equivalent at all', (pptx) => {
		pptx.defineSlideMaster({
			title: 'CORPUS_MASTER',
			background: { color: 'FFFFFF' },
			objects: [
				{ placeholder: { options: { name: 'title', type: 'title', x: 0.5, y: 0.4, w: 9, h: 1 }, text: 'Title' } },
				{ placeholder: { options: { name: 'body', type: 'body', x: 0.5, y: 1.6, w: 9, h: 3 }, text: 'Body' } },
			],
		})
		const slide = pptx.addSlide({ masterTitle: 'CORPUS_MASTER' })
		slide.addText('Inherited title', { placeholder: 'title' })
		slide.addText('Inherited body copy', { placeholder: 'body' })
	}),

	deck('notes', 'hard', 'speaker notes live on a separate part with its own master', (pptx) => {
		pptx.addSlide().addText('Slide with notes', { x: 1, y: 1, w: 6, h: 1 }).addNotes('Remember to mention the oracle.')
	}),

	deck('rotated-flipped', 'hard', 'rotation and flips compose in a way box layout cannot express', (pptx) => {
		const slide = pptx.addSlide()
		slide.addShape('triangle', { x: 1, y: 1, w: 2, h: 2, fill: { color: '250F6B' }, rotate: 30, objectName: 'rotated' })
		slide.addShape('triangle', {
			x: 4,
			y: 1,
			w: 2,
			h: 2,
			fill: { color: '9B1B30' },
			flipH: true,
			flipV: true,
			objectName: 'flipped',
		})
	}),

	deck('theme-color', 'hard', 'a scheme colour is a reference, not a value — it re-resolves on rebind', (pptx) => {
		pptx.theme = {
			headFontFace: 'Aptos Display',
			bodyFontFace: 'Aptos',
			colorScheme: { accent1: '250F6B', accent2: '9B1B30' },
		}
		const slide = pptx.addSlide()
		slide.addShape('rect', { x: 1, y: 1, w: 3, h: 2, fill: { color: 'accent1' }, objectName: 'themed' })
		slide.addText('Themed text', { x: 1, y: 3.2, w: 3, h: 0.6, color: 'accent2', objectName: 'themed-copy' })
	}),
]

export const PRIMITIVES: CorpusDeck[] = CORPUS.filter((entry) => entry.tier === 'primitive')
export const HARD: CorpusDeck[] = CORPUS.filter((entry) => entry.tier === 'hard')

/**
 * A deck of one labelled slide per entry, for the ordering checks: slide
 * identity has to be visible in the read model for "did these come back in
 * source order" to be answerable at all.
 */
export async function buildLabelledDeck(labels: string[]): Promise<Uint8Array> {
	const pptx = newDeck()
	for (const label of labels) {
		pptx.addSlide().addText(label, { x: 1, y: 1, w: 6, h: 1, fontSize: 32, objectName: label })
	}
	return bytesOf(pptx)
}

/** The writer instance behind {@link buildLabelledDeck}, for `appendSlides` (which takes a live producer). */
export function labelledProducer(labels: string[]): TsPptx {
	const pptx = newDeck()
	for (const label of labels) {
		pptx.addSlide().addText(label, { x: 1, y: 1, w: 6, h: 1, fontSize: 32, objectName: label })
	}
	return pptx
}

/**
 * Build every corpus deck once per test file. Generation is the slow part
 * (a full write per deck), and every deck is deterministic, so caching is safe.
 */
const cache = new Map<string, Uint8Array>()

export async function corpusBytes(entry: CorpusDeck): Promise<Uint8Array> {
	const hit = cache.get(entry.name)
	if (hit) return hit
	const bytes = await entry.build()
	cache.set(entry.name, bytes)
	return bytes
}
