/**
 * The corpus: the decks the oracle is asked about.
 *
 * Every deck here is **generated by `@shbernal/ts-pptx` itself**, and that is not
 * a convenience — it is the v1 input domain. The guarantee is scoped to decks
 * this pipeline can write, so generating the corpus from the writer makes the
 * corpus and the guarantee's scope the same set. Decks authored in PowerPoint
 * are a second tier, deferred.
 *
 * They are built by code rather than committed as `.pptx` binaries so the corpus
 * is reviewable in a diff and reproducible from source. Nothing here may depend
 * on the clock, the filesystem or randomness: a corpus that differs between runs
 * makes every downstream comparison unfalsifiable.
 *
 * Two tiers:
 *
 * - `primitive` — one deck per emit primitive. These are the constructs the IR
 *   is expected to model, so a difference is a defect.
 * - `hard` — one deck per known-hard feature. These are expected to take the
 *   carried lane or to arrive with fidelity notes at first; they are here so the
 *   coverage report can watch them move, not because they must pass today.
 */

import { ShapeType, TsPptx } from '@shbernal/ts-pptx'

/** A 1×1 PNG. Content is irrelevant; being real, small and constant is not. */
const PIXEL_PNG =
	'image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='

export type CorpusTier = 'primitive' | 'hard'

export interface CorpusDeck {
	/** Stable id — used as a snapshot key, so renaming one rewrites history. */
	name: string
	tier: CorpusTier
	/** What this deck is here to hold the pipeline to. */
	why: string
	build: () => Promise<Uint8Array>
}

/** A writer with deterministic deck properties: no clock, no host, no defaults that drift. */
function newDeck(): TsPptx {
	const pptx = new TsPptx()
	pptx.layout = 'LAYOUT_16x9'
	pptx.author = 'dom2pptx corpus'
	pptx.company = 'dom2pptx'
	pptx.subject = 'round-trip corpus'
	pptx.title = 'round-trip corpus'
	return pptx
}

async function bytesOf(pptx: TsPptx): Promise<Uint8Array> {
	return (await pptx.write({ outputType: 'uint8array' })) as Uint8Array
}

function deck(name: string, tier: CorpusTier, why: string, author: (pptx: TsPptx) => void | Promise<void>): CorpusDeck {
	return {
		name,
		tier,
		why,
		build: async () => {
			const pptx = newDeck()
			await author(pptx)
			return bytesOf(pptx)
		},
	}
}

export const CORPUS: CorpusDeck[] = [
	deck('text-box', 'primitive', 'runs, paragraph breaks and per-run character formatting', (pptx) => {
		pptx.addSlide().addText(
			[
				{ text: 'Round', options: { bold: true, color: '250F6B' } },
				{ text: '-trip', options: { italic: true, color: '9B1B30' } },
				{ text: '\nsecond paragraph', options: { breakLine: true, fontSize: 14 } },
			],
			{ x: 0.5, y: 0.5, w: 6, h: 2, fontSize: 24, align: 'left', objectName: 'copy' }
		)
	}),

	deck('autoshape', 'primitive', 'a preset geometry with an explicit fill and outline', (pptx) => {
		pptx.addSlide().addShape('roundRect', {
			x: 1,
			y: 1,
			w: 3,
			h: 1.5,
			fill: { color: 'DDE3F0' },
			line: { color: '250F6B', width: 2 },
			rectRadius: 0.2,
			objectName: 'card',
		})
	}),

	deck('custgeom', 'primitive', 'freeform path geometry — the case the SVG vectorizer produces', (pptx) => {
		pptx.addSlide().addShape(ShapeType.custGeom, {
			x: 1,
			y: 1,
			w: 3,
			h: 3,
			fill: { color: '9B1B30' },
			points: [
				{ x: 0, y: 0, moveTo: true },
				{ x: 3, y: 0 },
				{ x: 3, y: 3, curve: { type: 'cubic', x1: 2.5, y1: 1, x2: 2, y2: 2 } },
				{ close: true },
			],
			objectName: 'freeform',
		})
	}),

	deck('table', 'primitive', 'a grid with per-cell formatting and explicit column widths', (pptx) => {
		pptx.addSlide().addTable(
			[
				[
					{ text: 'Region', options: { bold: true, fill: { color: '250F6B' }, color: 'FFFFFF' } },
					{ text: 'Share', options: { bold: true, fill: { color: '250F6B' }, color: 'FFFFFF' } },
				],
				[{ text: 'EMEA' }, { text: '48%' }],
				[{ text: 'AMER' }, { text: '31%' }],
			],
			{ x: 0.5, y: 0.5, w: 6, colW: [3, 3], border: { type: 'solid', color: 'CCCCCC', width: 1 }, objectName: 'grid' }
		)
	}),

	deck('picture', 'primitive', 'embedded media — the case hash-addressed assets must survive', (pptx) => {
		pptx.addSlide().addImage({ data: PIXEL_PNG, x: 1, y: 1, w: 2, h: 2, objectName: 'photo' })
	}),

	deck('connector', 'primitive', 'a line with routing and an arrowhead, not a shape', (pptx) => {
		pptx.addSlide().addConnector({
			type: 'elbow',
			x1: 1,
			y1: 1,
			x2: 5,
			y2: 3,
			color: '250F6B',
			width: 2,
			endArrowType: 'triangle',
			objectName: 'link',
		})
	}),

	deck('gradient', 'primitive', 'a multi-stop gradient fill — no single colour to fall back on', (pptx) => {
		pptx.addSlide().addShape('rect', {
			x: 0.5,
			y: 0.5,
			w: 8,
			h: 2,
			fill: {
				type: 'gradient',
				gradient: {
					kind: 'linear',
					angle: 45,
					stops: [
						{ position: 0, color: '250F6B' },
						{ position: 50, color: '4A3F9B' },
						{ position: 100, color: '9B1B30' },
					],
				},
			},
			objectName: 'banner',
		})
	}),

	deck('group', 'primitive', 'nested shape identity — a note about a child must still match', (pptx) => {
		pptx
			.addSlide()
			.addGroup(
				[
					{ rect: { x: 1, y: 1, w: 2, h: 1, fill: { color: 'DDE3F0' }, objectName: 'group-plate' } },
					{ text: { text: 'Grouped', options: { x: 1.1, y: 1.1, w: 1.8, h: 0.8, objectName: 'group-label' } } },
				],
				{ objectName: 'cluster' }
			)
	}),

	deck(
		'nested-group',
		'primitive',
		'a group inside a group — the depth where child coordinate space goes wrong',
		(pptx) => {
			pptx.addSlide().addGroup(
				[
					{ rect: { x: 0.5, y: 0.5, w: 1, h: 1, fill: { color: 'DDE3F0' }, objectName: 'outer-plate' } },
					{
						group: {
							children: [
								{ rect: { x: 2, y: 0.8, w: 1, h: 0.6, fill: { color: '250F6B' }, objectName: 'inner-plate' } },
								{ text: { text: 'Deep', options: { x: 2.1, y: 0.85, w: 0.8, h: 0.5, objectName: 'inner-label' } } },
							],
							options: { objectName: 'inner' },
						},
					},
				],
				{ objectName: 'outer' }
			)
		}
	),

	deck(
		'hyperlink',
		'primitive',
		'a run whose link points at another slide — an identity the IR must resolve',
		(pptx) => {
			pptx
				.addSlide()
				.addText([{ text: 'Jump to the appendix', options: { hyperlink: { slide: 2, tooltip: 'Appendix' } } }], {
					x: 1,
					y: 1,
					w: 6,
					h: 1,
					objectName: 'link-source',
				})
			pptx.addSlide().addText([{ text: 'External', options: { hyperlink: { url: 'https://example.invalid/spec' } } }], {
				x: 1,
				y: 1,
				w: 6,
				h: 1,
				objectName: 'link-target',
			})
		}
	),

	deck('chart', 'hard', 'a full reader with no writer for every form — expected to be carried', (pptx) => {
		pptx.addSlide().addChart([{ name: 'Share', labels: ['EMEA', 'AMER', 'APAC'], values: [48, 31, 21] }], {
			type: 'bar',
			x: 1,
			y: 1,
			w: 6,
			h: 3.5,
			objectName: 'chart',
		})
	}),

	deck('layout-placeholder', 'hard', 'placeholder inheritance from a layout — no CSS equivalent at all', (pptx) => {
		pptx.defineSlideMaster({
			title: 'CORPUS_MASTER',
			background: { color: 'FFFFFF' },
			objects: [
				{ placeholder: { options: { name: 'title', type: 'title', x: 0.5, y: 0.4, w: 9, h: 1 }, text: 'Title' } },
				{ placeholder: { options: { name: 'body', type: 'body', x: 0.5, y: 1.6, w: 9, h: 3 }, text: 'Body' } },
			],
		})
		const slide = pptx.addSlide({ masterTitle: 'CORPUS_MASTER' })
		slide.addText('Inherited title', { placeholder: 'title' })
		slide.addText('Inherited body copy', { placeholder: 'body' })
	}),

	deck('notes', 'hard', 'speaker notes live on a separate part with its own master', (pptx) => {
		pptx.addSlide().addText('Slide with notes', { x: 1, y: 1, w: 6, h: 1 }).addNotes('Remember to mention the oracle.')
	}),

	deck('rotated-flipped', 'hard', 'rotation and flips compose in a way box layout cannot express', (pptx) => {
		const slide = pptx.addSlide()
		slide.addShape('triangle', { x: 1, y: 1, w: 2, h: 2, fill: { color: '250F6B' }, rotate: 30, objectName: 'rotated' })
		slide.addShape('triangle', {
			x: 4,
			y: 1,
			w: 2,
			h: 2,
			fill: { color: '9B1B30' },
			flipH: true,
			flipV: true,
			objectName: 'flipped',
		})
	}),

	deck('theme-color', 'hard', 'a scheme colour is a reference, not a value — it re-resolves on rebind', (pptx) => {
		pptx.theme = {
			headFontFace: 'Aptos Display',
			bodyFontFace: 'Aptos',
			colorScheme: { accent1: '250F6B', accent2: '9B1B30' },
		}
		const slide = pptx.addSlide()
		slide.addShape('rect', { x: 1, y: 1, w: 3, h: 2, fill: { color: 'accent1' }, objectName: 'themed' })
		slide.addText('Themed text', { x: 1, y: 3.2, w: 3, h: 0.6, color: 'accent2', objectName: 'themed-copy' })
	}),
]

export const PRIMITIVES: CorpusDeck[] = CORPUS.filter((entry) => entry.tier === 'primitive')
export const HARD: CorpusDeck[] = CORPUS.filter((entry) => entry.tier === 'hard')

/**
 * A deck of one labelled slide per entry, for the ordering checks: slide
 * identity has to be visible in the read model for "did these come back in
 * source order" to be answerable at all.
 */
export async function buildLabelledDeck(labels: string[]): Promise<Uint8Array> {
	const pptx = newDeck()
	for (const label of labels) {
		pptx.addSlide().addText(label, { x: 1, y: 1, w: 6, h: 1, fontSize: 32, objectName: label })
	}
	return bytesOf(pptx)
}

/** The writer instance behind {@link buildLabelledDeck}, for `appendSlides` (which takes a live producer). */
export function labelledProducer(labels: string[]): TsPptx {
	const pptx = newDeck()
	for (const label of labels) {
		pptx.addSlide().addText(label, { x: 1, y: 1, w: 6, h: 1, fontSize: 32, objectName: label })
	}
	return pptx
}

/**
 * Build every corpus deck once per test file. Generation is the slow part
 * (a full write per deck), and every deck is deterministic, so caching is safe.
 */
const cache = new Map<string, Uint8Array>()

export async function corpusBytes(entry: CorpusDeck): Promise<Uint8Array> {
	const hit = cache.get(entry.name)
	if (hit) return hit
	const bytes = await entry.build()
	cache.set(entry.name, bytes)
	return bytes
}
