/**
 * Generates the fidelity ledger page from the oracle's own reporter.
 *
 * The README claims the per-construct ledger is snapshotted so it cannot move
 * silently. This publishes it, and the way it is built is the point: the numbers
 * come from `test/oracle/coverage.ts` running over `test/corpus/decks.ts` — the
 * same inputs and the same computation the snapshot test uses. The page therefore
 * cannot say more than the oracle knows.
 *
 * It deliberately does **not** parse
 * `test/oracle/__snapshots__/coverage.test.ts.snap`. That file is fixed-width
 * padding for a human reading a diff; scraping it would work today and break the
 * first time someone adjusts a column. `formatCoverage` stays the snapshot's
 * business and this page formats its own.
 *
 * Nothing under `test/` is modified or added to for this. If the ledger ever
 * needs something the oracle does not already export, the answer is to stop:
 * the oracle is not the site's to reshape.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { CORPUS, corpusBytes } from '../../test/corpus/decks.ts'
import { type CoverageRow, coverageRow, unmatchableConstructs } from '../../test/oracle/coverage.ts'
import { viewDeck } from '../../test/oracle/roundtrip.ts'
import { LEDGER } from './docs-source.ts'
import { repoRoot } from './repo.ts'

/** Upstream's vocabulary, in upstream's order. Never a local synonym — see AGENTS.md. */
const DISPOSITIONS = ['dropped', 'flattened', 'approximated'] as const
const CAUSES = ['unread', 'unwritable', 'unsupported'] as const

const OUT = resolve(repoRoot, 'site', 'docs', `${LEDGER.slug}.md`)

interface Ledger {
	rows: CoverageRow[]
	unmatchable: string[]
}

const ledger = await measure()

mkdirSync(resolve(repoRoot, 'site', 'docs'), { recursive: true })
writeFileSync(OUT, page(ledger), 'utf8')
console.log(`build-ledger: ${ledger.rows.length} decks → site/docs/${LEDGER.slug}.md`)

/**
 * Measured on every run, with no cache behind it.
 *
 * The corpus is built in memory by the writer and read back through the script
 * tier — no filesystem, no rendering — and the whole seventeen take well under a
 * second. A cache was planned for this and would have bought nothing except a way
 * for the page to be quietly out of date, which is the one failure it must not
 * have.
 */
async function measure(): Promise<Ledger> {
	const rows: CoverageRow[] = []
	const unmatchable = new Set<string>()
	for (const entry of CORPUS) {
		const view = await viewDeck(await corpusBytes(entry))
		rows.push(coverageRow(entry.name, entry.tier, view.ir))
		for (const construct of unmatchableConstructs(view.ir.fidelity)) unmatchable.add(construct)
	}
	return { rows, unmatchable: [...unmatchable].sort() }
}

// ---------------------------------------------------------------------------
// The page
// ---------------------------------------------------------------------------

function page(ledger: Ledger): string {
	const { rows } = ledger
	return [
		'---',
		`title: '${LEDGER.title}'`,
		`description: '${LEDGER.description}'`,
		'editLink: false',
		'---',
		'',
		`<!-- Generated by site/scripts/build-ledger.ts from test/corpus/ and test/oracle/. Do not edit. -->`,
		'',
		`# ${LEDGER.title}`,
		'',
		scope(rows),
		'',
		'## Per deck',
		'',
		'Every deck name links to the playground with that deck loaded, so a row is',
		'something you can run rather than something you have to take on trust.',
		'',
		deckTable(rows),
		'',
		'## Where the losses sit',
		'',
		'Fidelity notes across the whole corpus, by **disposition** (what happened to the',
		'construct) × **cause** (why). Both axes are upstream `FidelityNote` values, not a',
		'local restatement of them: one vocabulary, so the differ and this page cannot',
		'drift apart.',
		'',
		'The cause is also the triage: `unread` and `unwritable` name a specific',
		'subsystem of the writer and are fixable there, while `unsupported` is a property',
		'of OOXML or of the output tier and will not move however much converter work',
		'happens.',
		'',
		matrix(rows),
		'',
		'## Constructs named',
		'',
		constructTable(rows),
		'',
		unmatchableSection(ledger),
		'',
	].join('\n')
}

function scope(rows: CoverageRow[]): string {
	const hard = rows.filter((row) => row.tier === 'hard').length
	return [
		'**What this covers, before any number below.** The round-trip guarantee is',
		'scoped to decks written by',
		'[`@shbernal/ts-pptx`](https://www.npmjs.com/package/@shbernal/ts-pptx), which is',
		`what these ${rows.length} decks are. Decks authored in PowerPoint are a deliberate`,
		'second tier and are **not gated** by any of this. See [Invariant R and the',
		'round-trip oracle](./round-trip) for what the gate does and does not promise.',
		'',
		'This table is not a pass/fail list, and reading it as one gets it backwards.',
		'"How many round-trips are green" says nothing while the supported subset is',
		'small: a converter that models three constructs and warns about everything else',
		'would be entirely green. What moves is the *shape* of the loss: notes leaving',
		'`dropped`, causes leaving `unread`, slides leaving the carried lane.',
		'',
		`That is also what the **hard** tier is for. ${hard} of the decks below are there`,
		'to be watched moving, not to pass today; they hold features with a known-hard or',
		'absent path through the writer, and they earn their place by making a regression',
		'visible rather than by being green.',
	].join('\n')
}

function deckTable(rows: CoverageRow[]): string {
	const lines = [
		'| Deck | Tier | Slides | Write calls | Notes |',
		'| --- | --- | --- | --- | --- |',
		...rows.map((row) => {
			const notes = Object.values(row.cells).reduce((total, count) => total + count, 0)
			const slides = `${row.slides} (${row.authored} authored / ${row.carried} carried)`
			return `| [\`${row.deck}\`](/playground?deck=${row.deck}) | ${tier(row.tier)} | ${slides} | ${row.calls} | ${notes} |`
		}),
	]
	return lines.join('\n')
}

function matrix(rows: CoverageRow[]): string {
	const totals: Record<string, number> = {}
	for (const row of rows) {
		for (const [key, count] of Object.entries(row.cells)) totals[key] = (totals[key] ?? 0) + count
	}
	return [
		`| | ${CAUSES.map((cause) => `\`${cause}\``).join(' | ')} |`,
		`| --- | ${CAUSES.map(() => '---').join(' | ')} |`,
		...DISPOSITIONS.map(
			(disposition) =>
				`| \`${disposition}\` | ${CAUSES.map((cause) => totals[`${disposition}/${cause}`] ?? 0).join(' | ')} |`
		),
	].join('\n')
}

function constructTable(rows: CoverageRow[]): string {
	const named = rows.filter((row) => row.constructs.length > 0)
	if (named.length === 0) return 'No deck in the corpus currently carries a fidelity note.'
	return [
		'| Deck | Constructs |',
		'| --- | --- |',
		...named.map((row) => `| \`${row.deck}\` | ${row.constructs.map((c) => `\`${c}\``).join(', ')} |`),
	].join('\n')
}

/**
 * A note whose construct the differ has no matcher for can never declare
 * anything: it sits unmatched forever while the difference it was meant to
 * account for is reported as a defect. The oracle gates this at zero, so the
 * honest thing to publish is the zero rather than nothing at all.
 */
function unmatchableSection(ledger: Ledger): string {
	if (ledger.unmatchable.length === 0) {
		return [
			'## Notes the differ cannot match',
			'',
			'**None.** Every fidelity note in the corpus names a construct the differ has a',
			'matcher for. A note it does not know is inert (it looks like honesty while',
			'excusing nothing), so the oracle holds this at zero.',
		].join('\n')
	}
	return [
		'## Notes the differ cannot match',
		'',
		'These constructs are named by a note the differ has no matcher for, so the note',
		'declares nothing and the difference it was meant to account for is reported as a',
		'defect:',
		'',
		...ledger.unmatchable.map((construct) => `- \`${construct}\``),
	].join('\n')
}

function tier(value: string): string {
	return value === 'hard' ? '**hard**' : value
}
